name: Check
on:
  push:
    branches:
      - 'main'
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Check event
        run: echo "${CURRENT_EVENT}" | jq
        env:
          CURRENT_EVENT: ${{ toJSON(github.event) }}
      - name: Check event file
        run: jq < "${GITHUB_EVENT_PATH}"
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: 'package.json'
      - run: npm ci
      - run: npm run ci

  check-dist:
    # Copied from https://github.com/actions/typescript-action/blob/main/.github/workflows/check-dist.yml
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: 'package.json'
      - run: npm ci
      - run: npm run bundle
      - name: Compare Directories
        id: diff
        run: |
          if [ ! -d dist/ ]; then
            echo "Expected dist/ directory does not exist.  See status below:"
            ls -la ./
            exit 1
          fi
          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build"
            exit 1
          fi

  local-action:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs:
      - check
      - check-dist
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: './'
        id: test-action
        with:
          save-key: true
      - name: Print output
        shell: python
        run: |
          import os
          print(os.environ.get("obtained_key", "NOT_FOUND"))
        env:
          obtained_key: ${{ steps.test-action.outputs.key }}

  local-action2:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    needs:
      - check
      - check-dist
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: './'
        id: test-action
        with:
          save-key: false
      - name: Print output
        shell: python
        run: |
          import os
          print(os.environ.get("obtained_key", "NOT_FOUND"))
        env:
          obtained_key: ${{ steps.test-action.outputs.key }}
